import json
def mock(vm,answer,left='Article 1 access. Article 2 appeal within 20 days.',right='Article 1 access. Article 2 appeal within 30 days.'):
 vm.mock_web(r'left\.example',{'status':200,'body':left});vm.mock_web(r'right\.example',{'status':200,'body':right});vm.mock_llm(r'.*ParallelStatute official-text parity review.*',json.dumps(answer))
def test_drift_and_single_side_repair(direct_vm,direct_deploy,direct_alice,direct_bob):
 direct_vm.warp('2035-01-01T00:00:00+00:00');direct_vm.sender=direct_alice;c=direct_deploy('contracts/contract.py');c.register_instrument('charter-4','0x'+direct_bob.hex(),'Harbor access charter','English','Tamazight',['Access right','Appeal deadline'],'https://left.example/charter','https://right.example/charter',600);bad={'codes':['EQUIVALENT','MATERIAL_DRIFT'],'notes':['Access matches.','Deadlines differ.'],'summary':'One material deadline drift.'};mock(direct_vm,bad);direct_vm.sender=direct_bob;c.audit_parity('charter-4');assert c.get_instrument('charter-4')['state']=='DRIFT';direct_vm.sender=direct_alice;direct_vm.clear_mocks();good={'codes':['EQUIVALENT','EQUIVALENT'],'notes':['Access matches.','Deadline matches.'],'summary':'Both sections are equivalent.'};mock(direct_vm,good,right='Article 1 access. Article 2 appeal within 20 days.');c.repair_text('charter-4','RIGHT','https://right.example/charter-v2');assert c.get_instrument('charter-4')['state']=='RESTORED'
def test_auditor_only_and_forged_omission(direct_vm,direct_deploy,direct_alice,direct_bob):
 direct_vm.sender=direct_alice;c=direct_deploy('contracts/contract.py');c.register_instrument('z','0x'+direct_bob.hex(),'A complete official instrument','French','Arabic',['Right one','Duty two'],'https://left.example/z','https://right.example/z',600);answer={'codes':['EQUIVALENT','EQUIVALENT'],'notes':['Same right.','Same duty.'],'summary':'Parity.'};mock(direct_vm,answer)
 with direct_vm.expect_revert('independent auditor'):c.audit_parity('z')
 direct_vm.sender=direct_bob;x=c.instruments['Z'];r=c._compare(x,x.left_url,x.right_url);assert direct_vm.run_validator(leader_result=r) is True;forged=dict(r);forged['codes']=['EQUIVALENT'];assert direct_vm.run_validator(leader_result=forged) is False
